//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuTopologyArgs) DeepCopyInto(out *GpuTopologyArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.PermitWaitingTimeSeconds != nil {
		in, out := &in.PermitWaitingTimeSeconds, &out.PermitWaitingTimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ScoreSameNode != nil {
		in, out := &in.ScoreSameNode, &out.ScoreSameNode
		*out = new(int64)
		**out = **in
	}
	if in.ScoreSameNVLinkDomain != nil {
		in, out := &in.ScoreSameNVLinkDomain, &out.ScoreSameNVLinkDomain
		*out = new(int64)
		**out = **in
	}
	if in.ScoreSameRack != nil {
		in, out := &in.ScoreSameRack, &out.ScoreSameRack
		*out = new(int64)
		**out = **in
	}
	if in.ScoreDifferentRack != nil {
		in, out := &in.ScoreDifferentRack, &out.ScoreDifferentRack
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuTopologyArgs.
func (in *GpuTopologyArgs) DeepCopy() *GpuTopologyArgs {
	if in == nil {
		return nil
	}
	out := new(GpuTopologyArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuTopologyArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
